version: "3"

services:
  backend:
    image: calendar:develop
    ports:
      - "8080:8080"
      - "50051:50051"
    env_file:
      - ../.env
    depends_on:
      - db
      - migrate
    networks:
      - calendar

  scheduler:
    image: calendar_scheduler:develop
    env_file:
      - ../.env
    depends_on:
      - db
      - migrate
      - rabbit
    networks:
      - calendar

  sender:
    image: calendar_sender:develop
    env_file:
      - ../.env
    depends_on:
      - rabbit
    networks:
      - calendar

  db:
    image: postgres:11.14
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "calendar"
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker/postgres/calendar/calendar_db:/var/lib/postgresql
    networks:
      - calendar

  migrate:
    image: migrate/migrate:v4.15.0
    entrypoint: ["sh", "/migrate-entrypoint.sh"]
    volumes:
      - ../deployments/migrate-entrypoint.sh:/migrate-entrypoint.sh
      - ../migrations:/migrations:rw
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - calendar

  rabbit:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - calendar

networks:
  calendar:
    external:
      name: calendar
