[logger]
level = "INFO"

[server]
http_bind_address = ":8080"
http_read_timeout = "5s"
http_write_timeout = "5s"
http_idle_timeout = "5s"

[grpc]
grpc_listen_address = ":50051"

[storage]
type = "sql"
